
<h5>Company Branding and Information</h5>
<p style="margin: 5px 0px; font-size: 13px; ">Customize your ZenHours page by adding your company logo, your company name, change your color scheme and company information.</p>
<a href="/Admin/Hris/company-branding-information">Company Branding Information</a><br /><br />

<h5>Configurations</h5>
<div style="margin: 5px 0px; font-size: 13px; ">Enable or disable IP Lockdown and the effects of holidays, night differential and overtime on payroll. You can also edit the values for the late grace period, overtime increment , minimum number of hours for overtime, number of days punch alteration will be valid, and the number of rows seen per page for Manager, HR, Accountant and Admin Accounts.</div>


<a href="/Admin/Hris/company-branding-information">Set company configuration</a><br /><br />

<div style="font-weight: bold; margin-top: 2px; ">Holidays</div>
<div style="margin: 5px 0px; font-size: 11px; ">Edit and manage your list of holidays according to the company's work schedule. This feature also includes the type of holiday (regular, legal, special non-working, special working) and the value that salary is multiplied by when work occurs on that holiday.</div>

<a href="/Admin/Hris/holiday-configuration">Set holiday configuration</a><br /><br />

<div style="font-weight: bold; margin-top: 2px; ">Leave Template Management</div>

<div style="margin: 5px 0px; font-size: 11px; ">Customize and manage the kinds of leaves that are observed by your company and select the employees they are applicable to.</div>
<a href="/Admin/Hris/company-branding-information">Template Management</a><br /><br />

<div style="font-weight: bold; margin-top: 2px; ">IP Lockdown</div>
<div style="margin: 5px 0px; font-size: 11px; ">
Every internet connection has a unique IP address. In order to prevent employees from logging in and out when away from the office, you can activate IP Lockdown. When IP Lockdown is enabled only users from this internet connection can access ZenHours.
<br/>
Please note that IP addresses are subject to change. In case of this, HR, Accountant and Admin Accounts are exempted from IP Lockdown and will still be able to access ZenHours with a different IP address, allowing them to whitelist, or enable the desired IP address.</div>
<a href="/Admin/Hris/company-branding-information">IP Lockdown</a><br /><br />

