
  	<?php 
echo $this->Message."<br/>";
echo "Name :". $this->name."<br/>";
echo "Team :" . $this->team."<br/>";
echo "Manager :". $this->mngr."<br/>";

echo "Shift :" . $this->s_in." to ";
echo $this->s_out."<br/>";
echo $this->s_day."<br/>";
echo $this->day."<br/>";
echo $this->date;
																	


?><h4>Announcements </h4>
<?php foreach($this->ann as $value):
echo $value['tittle']."<br/>";
echo $value['date']."<br/>";
echo $value['message']."<br/>";
endforeach;
?><h4> Recent Punches</h4><br/>
	<div class="span2">Date<br/></div>
	<div class="span2">PunchIn<br/></div>
	<div class="span2">LunchOut<br/></div>
	<div class="span2">LunchIn <br/></div>
	<div class="span2">PunchOut<br/></div>

	 <?php foreach($this->punch as $p_value): 
	
	$date = explode(" ", $p_value['punchIn']);
  if($date[0] == null){ 	
echo $this->date_format;?>
<a id="p_in" class="li" href="/User/index/insert/">
       PunchIn
    </a>
<!-- <a id="l_out" class="li" href="/User/index/updatelout/">
       LunchOut
    </a>	
<a id="l_in" class="li" href="/User/index/updatelin/">
       LunchIn
    </a>
<a id="p_out" class="li" href="/User/index/updatepout/">
       PunchOut</a> -->
<?php  }


 if($date[0] == $this->date_format){?>

	<?php echo $date[0];?><br/>
	<?php if($p_value['punchIn'] == null){?><a id="p_in" class="li" href="/User/index/insert/">
       PunchIn
    </a><?php } echo $p_value['punchIn'];?><br/>
	<?php if($p_value['lunchOut'] == null && $p_value['punchIn'] != null){?><a id="l_out" class="li" href="/User/index/updatelout/">
       LunchOut
    </a><?php } echo $p_value['lunchOut'];?><br/>
	<?php if($p_value['lunchIn'] == null && $p_value['lunchOut'] != null){?><a id="l_in" class="li" href="/User/index/updatelin/">
       LunchIn
    </a><?php } echo $p_value['lunchIn'];?><br/>
	<?php if($p_value['punchOut'] == null && $p_value['lunchIn'] != null){?><a id="p_out" class="li" href="/User/index/updatepout/">
       PunchOut
    </a><?php } echo $p_value['punchOut'];?><br/><?php  
 } else{?>
	<?php echo $date[0];?><br/>
	<?php echo $p_value['punchIn'];?><br/>
	<?php echo $p_value['lunchOut'];?><br/>	
	<?php echo $p_value['lunchIn'];?><br/>
	<?php echo $p_value['punchOut'];?><br/>
<?php
 } endforeach;?>

																			



 


