<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">HRIS</a>
          <div class="nav-collapse collapse">
          
          <ul class="nav">  
             <li class="dropdown">
                      <a id="drop1" data-target="#" href="/page.html" role="button" class="dropdown-toggle" data-toggle="dropdown">Time Keeping<b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a tabindex="-1" href="http://google.com">Apply Punch Alteration</a></li>
                        <li><a tabindex="-1" href="#anotherAction">Punch Alteration History</a></li>
                        <li><a tabindex="-1" href="#">Punch History</a></li>
                        <li class="divider"></li>
                        <li><a tabindex="-1" href="#">Separated link</a></li>
                      </ul>
              </li>
            </ul> 

            <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li><a tabindex="-1" href="#">Edit Profile</a></li>
                        <li><a tabindex="-1" href="#">Change Password</a></li>
                        <li><a tabindex="-1" href="#">Logout</a></li>
                        
                      </ul>
                    </li>
            </ul>

            <ul class="nav">  
             <li class="dropdown">
                      <a id="drop1" data-target="#" href="/page.html" role="button" class="dropdown-toggle" data-toggle="dropdown">Overtime<b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a tabindex="-1" href="http://google.com">Overtime History</a></li>
                        <li><a tabindex="-1" href="#anotherAction">Apply Overtime</a></li>
                       
                      </ul>
              </li>
            </ul> 
            
            <ul class="nav">  
             <li class="dropdown">
                      <a id="drop1" data-target="#" href="/page.html" role="button" class="dropdown-toggle" data-toggle="dropdown">Leaves<b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a tabindex="-1" href="http://google.com">Leave History</a></li>
                        <li><a tabindex="-1" href="#anotherAction">Apply Leave</a></li>
                       
                      </ul>
              </li>
            </ul> 

            <ul class="nav">  
             <li class="dropdown">
                      <a id="drop1" data-target="#" href="/page.html" role="button" class="dropdown-toggle" data-toggle="dropdown">Payslips<b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li><a tabindex="-1" href="http://google.com">Payslip History</a></li>
                      </ul>
              </li>
            </ul> 
         
         
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

<div class="container">