  
      <div class="row">
        <div class="span4">
          
        </div>
        <div class="span4">
          <h2>Heading</h2>
          <?php  echo $this->form;
				       if(isset($this->successMsg)); 
				        echo $this->successMsg;
		 	 
		     		   if(isset($this->errorMessage))
				   		echo $this->errorMessage;

				   ?>
       </div>
        <div class="span4">
         
        </div>
      </div>


 
				

